services:
- type: web
  name: nublado-project
  env: python
  buildCommand: ./build.sh
  startCommand: gunicorn config.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: nubladoproject
        property: connectionString
    - key: DJANGO_SECRET_KEY
      fromGroup: nubladoproject
    - key: DJANGO_SETTINGS_MODULE
      fromGroup: nubladoproject
    - key: NUBLADO_BOT_TOKEN
      fromGroup: nubladoproject
    - key: NUBLADO_GROUP_ID
      fromGroup: nubladoproject
    - key: NUBLADO_GROUP_OWNER_ID
      fromGroup: nubladoproject
    - key: NUBLADO_REPO_ID
      fromGroup: nubladoproject
    - key: PORT
      fromGroup: nubladoproject

databases:
- name: nubladoproject
  databaseName: nubladoproject
  user: nubladoproject
