services:
- type: web
  name: nublado-project
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn config.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: nubladoproject
        property: connectionString
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings.production

databases:
- name: nubladoproject
  databaseName: nubladoproject
  user: nubladoproject
