databases:
- name: nubladoproject
  databaseName: nubladoproject
  user: nubladoproject

services:
- type: web
  name: nubladoproject
  env: python
  buildCommand: "./build.sh"
  startCommand: "gunicorn config.wsgi:application"
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: nubladoproject
        property: connectionString
    # - key: DJANGO_SECRET_KEY
    # - key: DJANGO_SETTINGS_MODULE
    # - key: NUBLADO_BOT_TOKEN
    # - key: NUBLADO_GROUP_ID
    # - key: NUBLADO_GROUP_OWNER_ID
    # - key: NUBLADO_REPO_ID
    # - key: PORT
    - fromGroup: nubladoproject